# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af2fdc8a7f0eab9273c9df4042781bcb159264df56fa644187f9db6a73bd5364b5f08e2bda2d3efd76f7feb236f1ca7777f834b8db7ff0d1d78d066fcde2b8d4

test:
  secret_key_base: 8ceef1a106f34fdd88fe31962a17468a6309b1526273c3c5ac8c1ffdba3db66b7adec965516b4805f20f2ad531024139c6087a9dee988f813db0a3f56efcb2b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
